apiVersion: v1
kind: Namespace
metadata:
  name: pragati
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: pragati
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rahuldocker99/pragati:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/login_system
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_SQL_INIT_MODE
              value: always
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: com.assignment.backend.shared.PostgreSQLJsonDialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SPRING_JPA_OPEN_IN_VIEW
              value: "false"
            - name: SPRING_MVC_VIEW_PREFIX
              value: /WEB-INF/views/
            - name: SPRING_MVC_VIEW_SUFFIX
              value: .jsp
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: pragati
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: pragati
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: login_system
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: pragati
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
  type: ClusterIP
