openapi: 3.0.0
info:
  title: Spring Boot API
  version: 1.0.0
paths:
  /v1/info:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Info'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Info'
  /v1/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    Info:
      type: object
      properties:
        username:
          type: string
        hobbies:
          type: string
        achievement:
          type: string
        personality:
          type: string
        to_be_improved_skills:
          type: string
        interest_topics:
          type: string
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
